name: Self Hosted Runner

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the script
        run: |
          if [[ "$(podman images -q iaccontainer 2> /dev/null)" == "" ]]; then
            podman build -t iaccontainer .
          fi  
          
          podman run -d --name my_new_iaccontainer \
            -e "GITHUB_OUTPUT=/github-output" \
            -v "$GITHUB_OUTPUT:/github-output" \
            iaccontainer:latest
          podman logs my_new_iaccontainer
          podman stop my_new_iaccontainer && podman rm my_new_iaccontainer
